version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mandala
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mandala"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.local
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app  # Должен быть правильный путь относительно docker-compose.yml
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - DB_URL=postgresql://user:password@postgres:5432/mandala
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
