name: Deploy to Yandex Cloud
#fix
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure YC CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh -o install.sh
          chmod +x install.sh
          ./install.sh -i $HOME/yandex-cloud -n                
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
          $HOME/yandex-cloud/bin/yc --version

      - name: Get IAM Token
        run: |
          ~/yandex-cloud/bin/yc config set token ${{ secrets.OUATH_TOKEN }}
          ~/yandex-cloud/bin/yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          ~/yandex-cloud/bin/yc config set folder-id ${{ secrets.YC_FOLDER_ID }}         
          YC_TOKEN=$(~/yandex-cloud/bin/yc iam create-token)
          echo "YC_IAM_TOKEN=$YC_TOKEN" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY_ID }}/miniapp-prod:latest .
          echo "${{ env.YC_IAM_TOKEN }}" | docker login -u iam --password-stdin cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY_ID }}
          docker push cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY_ID }}/miniapp-prod:latest

      - name: Update VM Container
        run: |
          ~/yandex-cloud/bin/yc compute instance update-container ${{ secrets.YC_VM_ID }} \
            --container-image cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY_ID }}/miniapp-prod:latest \
            --container-restart-policy always
