name: Deploy to Yandex Cloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download YC CLI
        run: |
          # Скачиваем бинарник yc из релиза
          curl -sSL -o yc https://github.com/pandanax/mandala/releases/download/v1.0.0/yc
          # Даем права на выполнение
          chmod +x yc
          # Создаем директорию и добавляем в PATH
          mkdir -p $HOME/.yc/bin
          mv yc $HOME/.yc/bin/
          echo "$HOME/.yc/bin" >> $GITHUB_PATH
          # Проверяем доступность yc через полный путь
          $HOME/.yc/bin/yc --version

      - name: Configure YC CLI
        run: |
          $HOME/.yc/bin/yc config set token ${{ secrets.YC_API_KEY }}

      - name: Generate IAM Token
        run: |
          YC_TOKEN=$($HOME/.yc/bin/yc iam create-token)
          echo "YC_IAM_TOKEN=$YC_TOKEN" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY_ID }}/mandala:latest .
          echo "${{ env.YC_IAM_TOKEN }}" | docker login -u iam --password-stdin cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY_ID }}
          docker push cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY_ID }}/mandala:latest

      - name: Update VM Container
        run: |
          $HOME/.yc/bin/yc compute instance update-container ${{ secrets.YC_VM_ID }} \
            --container-image cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY_ID }}/mandala:latest \
            --container-restart-policy always
